/*
 * ultrasonic_sensor.c
 *
 *  Created on: Oct 14, 2022
 *      Author: fatima
 */
#include"ultrasonic_sensor.h"
#include"icu.h"
#include"gpio.h"
#include <util/delay.h>
 uint8 g_edgeCount=0;
 uint16 g_timeHigh=0;
 uint16 g_distance=0;
/******************************************
 * ➢Initialize the ICU driver as required.
   ➢Setup the ICU call back function.
   ➢Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void Ultrasonic_init(void)
{
	/*initialize icu driver clock and edge  */
	Icu_ConfigType config ={F_CPU_8,RISING};
	Icu_init(&config);
	Icu_setCallBack(Ultrasonic_edgeProcessing);
	/*configure trigger pin as output pin */
	GPIO_setupPinDirection(TRIGGER_PORT,TRIGGER_PIN,PIN_OUTPUT);

}

/*
 * Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void)
{
	/*output a plus to the trigger pin for at least 10 us */
	GPIO_writePin(TRIGGER_PORT,TRIGGER_PIN,LOGIC_HIGH);
    _delay_us(11);
    GPIO_writePin(TRIGGER_PORT,TRIGGER_PIN,LOGIC_LOW);
}
uint16 Ultrasonic_readDistance(void){
	Ultrasonic_Trigger();
	while(g_timeHigh==0);
	/*
	 * the distanc (in cm)=(34000*time/2)
	 * the distanc (in cm)=17000*time
	 * time to execute 1 instruction is 1 us
	 * the distanc (in cm)=17000 x (TIMER value) x 1 x 10^-6 cm
	 * = timer value / 57.8
	 */
	g_distance= g_timeHigh /57.8 ;
	return g_distance;

}
/*
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor
 */
void Ultrasonic_edgeProcessing(void)
{
	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		Icu_clearTimerValue();
		/* Detect falling edge */
			Icu_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* Store the High time value */
		g_timeHigh = Icu_getInputCaptureValue();
		/* Detect rising edge */
		Icu_setEdgeDetectionType(RISING);
		g_edgeCount=0;
	}
}
